# Generated by Django 3.1.2 on 2020-10-31 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_answer_question'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['-date_pub']},
        ),
    ]
