# Generated by Django 3.1.2 on 2020-11-01 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_like'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='like',
            table='likes',
        ),
    ]
