# Generated by Django 3.1.2 on 2020-11-04 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_auto_20201101_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='vote',
            field=models.SmallIntegerField(choices=[(1, 'Like'), (-1, 'Dislike')], default=1),
            preserve_default=False,
        ),
    ]
