# Generated by Django 3.1.2 on 2020-11-04 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_like_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='rank',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='rank',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
