# Generated by Django 3.1.2 on 2020-11-04 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_auto_20201104_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='rank',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='rank',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
