# Generated by Django 3.1.2 on 2020-11-04 19:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0010_auto_20201104_1832'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Like',
            new_name='Vote',
        ),
        migrations.AlterModelTable(
            name='vote',
            table=None,
        ),
    ]
