os: linux

language: python

python:
  - "3.7"

env:
  secret_key=foobar

install:
  - pip install -r requirements.txt

before_script:
  - python manage.py migrate --noinput --settings=hasker.settings.local
  - python manage.py collectstatic  -c --noinput --settings=hasker.settings.local

script:
  - python manage.py test --settings=hasker.settings.local
