os: linux

language: python

python:
  - "3.7"

env:
  secret_key=foobar

install:
  - pip install -r requirements.txt

before_script:
  - python manage.py migrate --noinput
  - python manage.py collectstatic  -c --noinput

script:
  - python manage.py test
